/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoPi;

import controller.AluguelController;
import controller.ClienteController;
import controller.UsuarioController;
import controller.VeiculoController;
import java.sql.SQLException;
import java.sql.Date;
import java.util.Scanner;
import model.Aluguel;
import model.Cliente;
import model.Usuario;
import model.Veiculo;

public class App {
    public static void main(String[] args) throws SQLException {
           
        
        Cliente cliente = new Cliente();
        ClienteController clienteController = new ClienteController();        
        
        Veiculo veiculo = new Veiculo();
        VeiculoController veiculoController = new VeiculoController();
        
        Usuario usuario = new Usuario();
        UsuarioController usuarioController = new UsuarioController();

        Aluguel aluguel = new Aluguel();
        AluguelController aluguelController = new AluguelController();
         
       
        veiculo.setId(22);
        
        veiculoController.verificarVeiculoAlugado(veiculo);
    }
}
