/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.VeiculoController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import model.Veiculo;
import util.ButtonColumnCellRenderer;
import util.TableModelVeiculo;

/**
 *
 * @author User
 */
public class ScreenVeiculo extends javax.swing.JFrame {

    
    VeiculoController veiculoController = new VeiculoController();
    
    TableModelVeiculo veiculoModel;
    
     public ScreenVeiculo() {
        initComponents();
        initDataController();
        initComponetsModel();
        decorateTableTask();
        setLocationRelativeTo(null);
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscaVeiculo = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculo = new javax.swing.JTable();
        lblAviso = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnVoltarPainel = new javax.swing.JButton();
        lblControleDeClientes = new javax.swing.JLabel();
        lblBusqueVeiculo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);
        jPanel1.add(txtBuscaVeiculo);
        txtBuscaVeiculo.setBounds(235, 143, 238, 32);

        btnBusca.setBackground(new java.awt.Color(0, 46, 116));
        btnBusca.setForeground(new java.awt.Color(255, 255, 255));
        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusca);
        btnBusca.setBounds(316, 181, 71, 32);

        tableVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        tableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Alugado", "Nome ", "Consultar", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVeiculo.setGridColor(new java.awt.Color(255, 255, 255));
        tableVeiculo.setRowHeight(35);
        tableVeiculo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVeiculo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(129, 242, 467, 132);

        lblAviso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(255, 255, 255));
        lblAviso.setText("O veículo não está aparecendo?");
        jPanel1.add(lblAviso);
        lblAviso.setBounds(180, 390, 228, 19);

        btnCadastrar.setBackground(new java.awt.Color(0, 46, 116));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(478, 380, 87, 32);

        btnVoltarPainel.setBackground(new java.awt.Color(0, 46, 116));
        btnVoltarPainel.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarPainel.setText("Voltar para o Painel");
        btnVoltarPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPainelActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarPainel);
        btnVoltarPainel.setBounds(258, 452, 200, 80);

        lblControleDeClientes.setBackground(new java.awt.Color(255, 255, 255));
        lblControleDeClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblControleDeClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblControleDeClientes.setText("Controle de Veículos");
        jPanel1.add(lblControleDeClientes);
        lblControleDeClientes.setBounds(235, 61, 240, 32);

        lblBusqueVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        lblBusqueVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblBusqueVeiculo.setText("Busque o veiculo pelo nome ou Fabricante");
        jPanel1.add(lblBusqueVeiculo);
        lblBusqueVeiculo.setBounds(235, 121, 238, 16);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background7.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-9, -4, 730, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        RegistrationScreenVeiculo registrationScreenVeiculo = new RegistrationScreenVeiculo(this, rootPaneCheckingEnabled);
        registrationScreenVeiculo.setVisible(true);
        
        registrationScreenVeiculo.addWindowListener(new WindowAdapter() {
            
        public void windowClosed(WindowEvent e) {
                
        initDataController();
        initComponetsModel();
        decorateTableTask();
                         }
        }) ;
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVeiculoMouseClicked

        int rowIndex = tableVeiculo.rowAtPoint(evt.getPoint());
        int columnIndex = tableVeiculo.columnAtPoint(evt.getPoint());

        Veiculo veiculo = veiculoModel.getVeiculos().get(rowIndex);

        switch(columnIndex) {
            case 3 :          
                QueryScreenVeiculo queryScreenVeiculo = new QueryScreenVeiculo(this,rootPaneCheckingEnabled);
                
                queryScreenVeiculo.getTxtNumero().setText(veiculo.getNumero());
                queryScreenVeiculo.getTxtPlaca().setText(veiculo.getPlaca());
                queryScreenVeiculo.getTxtFabricante().setText(veiculo.getFabricante());
                queryScreenVeiculo.getTxtModelo().setText(veiculo.getModelo());
                queryScreenVeiculo.getCbAnoModelo().setSelectedItem(Integer.toString(veiculo.getAnoModelo()));
                queryScreenVeiculo.getCbQtdPortas().setSelectedItem(Integer.toString(veiculo.getQtdPortas()));
                queryScreenVeiculo.getTxtAcessorios().setText(veiculo.getAcessorios());
                queryScreenVeiculo.getLblShowId().setText(Integer.toString(veiculo.getId()));
                
                queryScreenVeiculo.setVisible(rootPaneCheckingEnabled);
                
                queryScreenVeiculo.addWindowListener(new WindowAdapter() {
            
                        public void windowClosed(WindowEvent e) {
                
                        initDataController();
                        initComponetsModel();
                        decorateTableTask();
                         }
                    }) ;
            break;
            case 4 :
 
           int resposta = JOptionPane.showOptionDialog(this,"Você realmente deseja apagar esse veiculo?","Confirmação",
           JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,
            null,
            new String[]{"Sim", "Não"},
            "Sim"
        );
        
        // Verifica qual botão foi pressionado
        if (resposta == JOptionPane.YES_OPTION) {
            veiculoController.removeById(veiculo.getId());
            veiculoModel.getVeiculos().remove(veiculo);
            initDataController();
            initComponetsModel();
            decorateTableTask();
        } 
            break;
        }
    }//GEN-LAST:event_tableVeiculoMouseClicked

    private void btnVoltarPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPainelActionPerformed
        // TODO add your handling code here:

        ScreenPainel painelScreen = new ScreenPainel();
        dispose();
        painelScreen.setVisible(true);
    }//GEN-LAST:event_btnVoltarPainelActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed

        initComponetsModel(txtBuscaVeiculo.getText());
        decorateTableTask();
        
      
    }//GEN-LAST:event_btnBuscaActionPerformed

    
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenVeiculo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltarPainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblBusqueVeiculo;
    private javax.swing.JLabel lblControleDeClientes;
    private javax.swing.JTable tableVeiculo;
    private javax.swing.JTextField txtBuscaVeiculo;
    // End of variables declaration//GEN-END:variables

     public void decorateTableTask() {
         tableVeiculo.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
         tableVeiculo.getTableHeader().setBackground(new Color(42, 47, 79));
         tableVeiculo.getTableHeader().setForeground(new Color(255, 255, 255));
         tableVeiculo.setAutoCreateRowSorter(true);

         
     
         
         tableVeiculo.getColumnModel().getColumn(3).setCellRenderer(new ButtonColumnCellRenderer("edit"));
         tableVeiculo.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("delete"));
     }
     
     public void initDataController() {
         
         veiculoController = new VeiculoController();
     }
     
     public void initComponetsModel() {

         veiculoModel = new TableModelVeiculo();
         tableVeiculo.setModel(veiculoModel);
         
          loadVeiculos();   
     }
     
     public void initComponetsModel(String model) {

         veiculoModel = new TableModelVeiculo();
         tableVeiculo.setModel(veiculoModel);
         
          loadVeiculos(model);   
     }
     
     public void loadVeiculos() {
         
       List<Veiculo> veiculos = veiculoController.getAll();
       veiculoModel.setVeiculos(veiculos);
    }
     
     public void loadVeiculos(String modelo) {
         
       List<Veiculo> veiculos = veiculoController.getAllByModelo(modelo);
       veiculoModel.setVeiculos(veiculos);
     }
    
}
