/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Usuario;

/**
 *
 * @author User
 */
public class ScreenPainel extends javax.swing.JFrame {

    /**
     * Creates new form PainelScreen
     */
    public ScreenPainel() {
        initComponents();
        setLocationRelativeTo(null);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JPanel();
        lblPainel = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        lblVeiculos = new javax.swing.JLabel();
        btnVeiculo = new javax.swing.JButton();
        lblUsuarios = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        lblAlugueis = new javax.swing.JLabel();
        btnAlugueis = new javax.swing.JButton();
        btnFaturamento = new javax.swing.JButton();
        lblAlugueis1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Painel.setLayout(null);

        lblPainel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPainel.setForeground(new java.awt.Color(255, 255, 255));
        lblPainel.setText("Painel de Controle");
        Painel.add(lblPainel);
        lblPainel.setBounds(148, 38, 212, 32);

        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setText("Clientes");
        Painel.add(lblCliente);
        lblCliente.setBounds(86, 127, 60, 16);

        btnCliente.setBackground(new java.awt.Color(0, 46, 116));
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("Acessar Clientes");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        Painel.add(btnCliente);
        btnCliente.setBounds(26, 149, 178, 70);

        lblVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        lblVeiculos.setText("Veículos");
        Painel.add(lblVeiculos);
        lblVeiculos.setBounds(83, 237, 49, 16);

        btnVeiculo.setBackground(new java.awt.Color(0, 46, 116));
        btnVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnVeiculo.setText("Acessar Veículos");
        btnVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculoActionPerformed(evt);
            }
        });
        Painel.add(btnVeiculo);
        btnVeiculo.setBounds(26, 259, 178, 71);

        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setText("Usuários");
        Painel.add(lblUsuarios);
        lblUsuarios.setBounds(373, 127, 51, 16);

        btnUsuarios.setBackground(new java.awt.Color(0, 46, 116));
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Acessar Usuários");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        Painel.add(btnUsuarios);
        btnUsuarios.setBounds(308, 149, 178, 70);

        lblAlugueis.setForeground(new java.awt.Color(255, 255, 255));
        lblAlugueis.setText("Aluguéis");
        Painel.add(lblAlugueis);
        lblAlugueis.setBounds(368, 237, 49, 16);

        btnAlugueis.setBackground(new java.awt.Color(0, 46, 116));
        btnAlugueis.setForeground(new java.awt.Color(255, 255, 255));
        btnAlugueis.setText("Acessar Aluguéis");
        btnAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugueisActionPerformed(evt);
            }
        });
        Painel.add(btnAlugueis);
        btnAlugueis.setBounds(308, 259, 178, 71);

        btnFaturamento.setBackground(new java.awt.Color(0, 46, 116));
        btnFaturamento.setForeground(new java.awt.Color(255, 255, 255));
        btnFaturamento.setText("Acessar Faturamento");
        btnFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturamentoActionPerformed(evt);
            }
        });
        Painel.add(btnFaturamento);
        btnFaturamento.setBounds(170, 364, 178, 66);

        lblAlugueis1.setForeground(new java.awt.Color(255, 255, 255));
        lblAlugueis1.setText("Faturamento");
        Painel.add(lblAlugueis1);
        lblAlugueis1.setBounds(220, 340, 100, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background4.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Painel.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
       
        ScreenCliente clienteScreen = new ScreenCliente();
        
        dispose();
        clienteScreen.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculoActionPerformed
      
        ScreenVeiculo veiculoScreen = new ScreenVeiculo();
        
        dispose();
        veiculoScreen.setVisible(true);
        
    }//GEN-LAST:event_btnVeiculoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
 
        ScreenUsuario screenUsuario = new ScreenUsuario();
        
        dispose();
        screenUsuario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugueisActionPerformed
 
       ScreenAluguel screenAluguel = new ScreenAluguel();
       
       dispose();
       
       screenAluguel.setVisible(true);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlugueisActionPerformed

    private void btnFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturamentoActionPerformed

      ScreenFaturamento screenFaturamento = new ScreenFaturamento();
      
      dispose();
      
      screenFaturamento.setVisible(true);
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFaturamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btnAlugueis;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFaturamento;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlugueis;
    private javax.swing.JLabel lblAlugueis1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblPainel;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblVeiculos;
    // End of variables declaration//GEN-END:variables
}
