/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AluguelController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author User
 */
public class ScreenFaturamento extends javax.swing.JFrame {

    MaskFormatter mf = null;   
    
    public ScreenFaturamento() {
        initComponents();
        setLocationRelativeTo(null);
    
         try {
        mf = new MaskFormatter("####-##-##");
        mf.setPlaceholderCharacter('_');
        } catch (ParseException e) {
        e.printStackTrace();
        }
        
        txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mf));   
        txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mf)); 
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFaturamento = new javax.swing.JLabel();
        lblExibirFaturamento = new javax.swing.JLabel();
        lblTituloFaturamento = new javax.swing.JLabel();
        btnExibirFaturamento = new javax.swing.JButton();
        txtDataInicial = new javax.swing.JFormattedTextField();
        txtDataFinal = new javax.swing.JFormattedTextField();
        lblDataEntrega = new javax.swing.JLabel();
        lblDataAluguel = new javax.swing.JLabel();
        btnVoltarPainel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lblFaturamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFaturamento.setForeground(new java.awt.Color(255, 255, 255));
        lblFaturamento.setText("Faturamento Total nesse Período:");
        jPanel1.add(lblFaturamento);
        lblFaturamento.setBounds(30, 270, 297, 24);

        lblExibirFaturamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblExibirFaturamento.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblExibirFaturamento);
        lblExibirFaturamento.setBounds(330, 270, 77, 24);

        lblTituloFaturamento.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloFaturamento.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTituloFaturamento.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloFaturamento.setText("Faturamento");
        jPanel1.add(lblTituloFaturamento);
        lblTituloFaturamento.setBounds(190, 50, 145, 32);

        btnExibirFaturamento.setBackground(new java.awt.Color(0, 46, 116));
        btnExibirFaturamento.setForeground(new java.awt.Color(255, 255, 255));
        btnExibirFaturamento.setText("Exibir Faturamento");
        btnExibirFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirFaturamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnExibirFaturamento);
        btnExibirFaturamento.setBounds(200, 200, 148, 47);

        txtDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicialActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataInicial);
        txtDataInicial.setBounds(120, 150, 125, 30);

        txtDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFinalActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataFinal);
        txtDataFinal.setBounds(310, 150, 125, 30);

        lblDataEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblDataEntrega.setText("Data Final");
        jPanel1.add(lblDataEntrega);
        lblDataEntrega.setBounds(310, 120, 55, 16);

        lblDataAluguel.setForeground(new java.awt.Color(255, 255, 255));
        lblDataAluguel.setText("Data Inicial");
        jPanel1.add(lblDataAluguel);
        lblDataAluguel.setBounds(120, 120, 62, 16);

        btnVoltarPainel1.setBackground(new java.awt.Color(0, 46, 116));
        btnVoltarPainel1.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarPainel1.setText("Voltar para o Painel");
        btnVoltarPainel1.setBorder(null);
        btnVoltarPainel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPainel1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarPainel1);
        btnVoltarPainel1.setBounds(160, 360, 230, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background9.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-9, -4, 670, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialActionPerformed

    private void txtDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalActionPerformed

    private void btnExibirFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirFaturamentoActionPerformed
 
       
        AluguelController aluguelController = new AluguelController();
        
        
        String dataString = txtDataInicial.getValue().toString();
        String dataString2 = txtDataFinal.getValue().toString();
        
        
        Date dataFormatada = null;
        Date dataFormatada2 = null;
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
             dataFormatada = sdf.parse(dataString);
             dataFormatada2 = sdf.parse(dataString2);
         } catch (ParseException ex) {
             Logger.getLogger(RegistrationScreenAluguel.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        if ( (txtDataInicial.getText().isEmpty() ) || ( txtDataFinal.getText().isEmpty() )) {

            JOptionPane.showMessageDialog(null, "Existem Informações sem atribuição, por favor preencha todos os dados");
            return;

        } else {
                    
                            
        float valor = aluguelController.ExibirFaturamento(dataFormatada, dataFormatada2);

        lblExibirFaturamento.setText(Float.toString(valor));

        }
        
        
        



        // TODO add your handling code here:
    }//GEN-LAST:event_btnExibirFaturamentoActionPerformed

    private void btnVoltarPainel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPainel1ActionPerformed
        // TODO add your handling code here:

        ScreenPainel painelScreen = new ScreenPainel();
        dispose();
        painelScreen.setVisible(true);
    }//GEN-LAST:event_btnVoltarPainel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenFaturamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibirFaturamento;
    private javax.swing.JButton btnVoltarPainel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataAluguel;
    private javax.swing.JLabel lblDataEntrega;
    private javax.swing.JLabel lblExibirFaturamento;
    private javax.swing.JLabel lblFaturamento;
    private javax.swing.JLabel lblTituloFaturamento;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
